[package]
name = "asm-lisp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.4"
# dynasm = "2.0.0"
# dynasmrt = "2.0.0"
lazy_static = "1.4.0"
# libc = "0.2"
